[package]
name = "contender-new-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-node-bindings = "1.0.25"
contender_core = { path = "../../contender/crates/core" }
contender_report = { path = "../../contender/crates/report" }
contender_testfile = { path = "../../contender/crates/testfile" }
contender_engine_provider = { path = "../../contender/crates/engine_provider" }
contender_sqlite = { path = "../../contender/crates/sqlite_db" }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
